name: Release-pr

permissions:
  pull-requests: write
  contents: write

on:
  workflow_dispatch:
  repository_dispatch:
    types: [publish]

jobs:
  release-pr:
    name: Release-pr
    runs-on: ubuntu-latest
    environment: Cargo
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: initial submodule
        run: 
          git submodule update --init
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Run release-plz
        uses: MarcoIeni/release-plz-action@v0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        with: 
          command: release-pr
